USE MyCompany;

DROP FUNCTION dbo.vlr_medio;

CREATE FUNCTION VLR_MEDIO(@MED INT)
RETURNS DECIMAL(8,2)
AS
BEGIN
DECLARE @MEDIA DECIMAL(8,2)
SELECT @MEDIA = (Am1 + Am2 + Am3 + Am4 + Am5)/5 
FROM MED_PUP
WHERE ID_MED = @MED
RETURN @MEDIA
END

CREATE FUNCTION VLR_MEDIOH(@MED INT)
RETURNS DECIMAL(8,2)
AS
BEGIN
DECLARE @MEDIA DECIMAL(8,2)
SELECT @MEDIA = (Am1 + Am2 + Am3 + Am4 + Am5)/5 
FROM MED_HEART
WHERE ID_MED = @MED
RETURN @MEDIA
END