CREATE DATABASE MyCompany;

use MyCompany;

DROP TABLE FUNCIONÁRIOS;
DROP TABLE VIAGENS;
DROP TABLE MED_PUP;
DROP TABLE MED_HEART;

CREATE TABLE FUNCIONÁRIOS(
ID_FUNC INT IDENTITY PRIMARY KEY,
fNAME NVARCHAR(50),
lNAME NVARCHAR(50),
);

CREATE TABLE VIAGENS(
ID_VIAGEM INT IDENTITY PRIMARY KEY,
FK_ID_FUNC INT,
DESTINO NVARCHAR(50),
CONSTRAINT FK_ID_FUNC FOREIGN KEY (FK_ID_FUNC) REFERENCES FUNCIONÁRIOS (ID_FUNC),
);


DROP TABLE MED_PUP;

CREATE TABLE MED_PUP(
ID_MED INT IDENTITY PRIMARY KEY,
FK_ID_VIAGEM INT,
MED_DATE DATE,
MED_TIME TIME,
AM1 DECIMAL(8,2),
AM2 DECIMAL(8,2),
AM3 DECIMAL(8,2),
AM4 DECIMAL(8,2),
AM5 DECIMAL(8,2),
MEDIA NVARCHAR(50),
CONSTRAINT FK_ID_VIAGEMP FOREIGN KEY (FK_ID_VIAGEM) REFERENCES VIAGENS (ID_VIAGEM),
);

DROP TABLE MED_HEART;

CREATE TABLE MED_HEART(
ID_MED INT IDENTITY PRIMARY KEY,
FK_ID_VIAGEM INT,
MED_DATE DATE,
MED_TIME TIME,
AM1 DECIMAL(8,2),
AM2 DECIMAL(8,2),
AM3 DECIMAL(8,2),
AM4 DECIMAL(8,2),
AM5 DECIMAL(8,2),
MEDIA NVARCHAR(50),
CONSTRAINT FK_ID_VIAGEMH FOREIGN KEY (FK_ID_VIAGEM) REFERENCES VIAGENS (ID_VIAGEM),
);


