USE MyCompany;

SELECT * FROM FUNCIONÁRIOS;
SELECT * FROM VIAGENS;
SELECT * FROM MED_PUP;
SELECT * FROM MED_HEART;

INSERT INTO FUNCIONÁRIOS(fNAME, lNAME) VALUES ('Willam','Castro');
INSERT INTO FUNCIONÁRIOS(fNAME, lNAME) VALUES ('Tiago','Santos');
INSERT INTO FUNCIONÁRIOS(fNAME, lNAME) VALUES ('Matheus','Barbosa');
INSERT INTO FUNCIONÁRIOS(fNAME, lNAME) VALUES ('Mayara','Christina');

INSERT INTO VIAGENS(FK_ID_FUNC, DESTINO) VALUES (2, 'SANTO ANDRÉ');
INSERT INTO VIAGENS(FK_ID_FUNC, DESTINO) VALUES (1, 'OSASCO');
INSERT INTO VIAGENS(FK_ID_FUNC, DESTINO) VALUES (3, 'HELIÓPOLIS');
INSERT INTO VIAGENS(FK_ID_FUNC, DESTINO) VALUES (4, 'GUARULHOS');

SELECT DESTINO
FROM VIAGENS
INNER JOIN FUNCIONÁRIOS
ON VIAGENS.FK_ID_FUNC = FUNCIONÁRIOS.ID_FUNC;

DECLARE @NOME NVARCHAR(50) = 'Willam';
DECLARE @ID_VIAGEM NVARCHAR(50) = 2;

SELECT ID_MED, MEDIA FROM MED_PUP
INNER JOIN VIAGENS
ON MED_PUP.FK_ID_VIAGEM = VIAGENS.ID_VIAGEM
INNER JOIN FUNCIONÁRIOS
ON VIAGENS.FK_ID_FUNC = FUNCIONÁRIOS.ID_FUNC
WHERE fNAME = @NOME AND ID_VIAGEM = @ID_VIAGEM;

DECLARE @NOME NVARCHAR(50) = 'Willam';
DECLARE @ID_VIAGEM NVARCHAR(50) = 2;

SELECT ID_MED, MEDIA FROM MED_HEART
INNER JOIN VIAGENS
ON MED_HEART.FK_ID_VIAGEM = VIAGENS.ID_VIAGEM
INNER JOIN FUNCIONÁRIOS
ON VIAGENS.FK_ID_FUNC = FUNCIONÁRIOS.ID_FUNC
WHERE fNAME = @NOME AND ID_VIAGEM = @ID_VIAGEM;


